name: Release

on:
  release:
    types: [published]

env:
  YARN_CHECKSUM_BEHAVIOR: update

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.release.prerelease && 'beta' || 'main' }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Publish with semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_REF: ${{ github.event.release.prerelease && 'refs/heads/beta' || 'refs/heads/main' }}
          GITHUB_REF_NAME: ${{ github.event.release.prerelease && 'beta' || 'main' }}
          GITHUB_REF_TYPE: branch
        run: npx semantic-release
