name: Release

on:
  release:
    types: [published]

env:
  YARN_CHECKSUM_BEHAVIOR: update

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.release.prerelease && 'beta' || 'main' }}

      - name: Ensure beta branch checkout
        if: ${{ github.event.release.prerelease == true }}
        run: |
          git fetch origin beta --depth=1
          git checkout beta
          git reset --hard origin/beta

      - name: Ensure main branch checkout
        if: ${{ github.event.release.prerelease != true }}
        run: |
          git fetch origin main --depth=1
          git checkout main
          git reset --hard origin/main

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Publish with semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          if [ "${{ github.event.release.prerelease }}" = "true" ]; then
            npx semantic-release
          else
            npx semantic-release
          fi
